export const buttons = [
  { id: '1', type: 'clear', value: 'AC' },
  { id: '2', type: 'delete', value: 'C' },
  { id: '3', type: 'posneg', value: '±' },
  { id: '4', type: 'operation', value: '%' },
  { id: '5', type: 'operation', value: '÷' },
  { id: '6', type: 'number', value: ' ' },
  { id: '7', type: 'number', value: '7' },
  { id: '8', type: 'number', value: '8' },
  { id: '9', type: 'number', value: '9' },
  { id: '10', type: 'operation', value: '×' },
  { id: '11', type: 'number', value: ' ' },
  { id: '12', type: 'number', value: '4' },
  { id: '13', type: 'number', value: '5' },
  { id: '14', type: 'number', value: '6' },
  { id: '15', type: 'operation', value: '-' },
  { id: '16', type: 'dot', value: '.' },
  { id: '17', type: 'number', value: '1' },
  { id: '18', type: 'number', value: '2' },
  { id: '19', type: 'number', value: '3' },
  { id: '20', type: 'operation', value: '+' },
  { id: '21', type: 'parenthesis', value: '(' },
  { id: '22', type: 'number', value: '0' },
  { id: '23', type: 'parenthesis', value: ')' },
  { id: '24', type: 'evaluate', value: '=' },
];
