export const BUTTONS = [
  { type: 'clear', value: 'AC' },
  { type: 'delete', value: 'C' },
  { type: 'posneg', value: '±' },
  { type: 'operation', value: '%' },
  { type: 'operation', value: '÷' },
  { type: 'clear-history', value: 'CH' },
  { type: 'number', value: '7' },
  { type: 'number', value: '8' },
  { type: 'number', value: '9' },
  { type: 'operation', value: '×' },
  { type: 'clear-all', value: 'CA' },
  { type: 'number', value: '4' },
  { type: 'number', value: '5' },
  { type: 'number', value: '6' },
  { type: 'operation', value: '-' },
  { type: 'dot', value: '.' },
  { type: 'number', value: '1' },
  { type: 'number', value: '2' },
  { type: 'number', value: '3' },
  { type: 'operation', value: '+' },
  { type: 'parenthesis', value: '(' },
  { type: 'number', value: '0' },
  { type: 'parenthesis', value: ')' },
  { type: 'evaluate', value: '=' },
];

export const PRIORITIES = {
  default: 0,
  '+': 1,
  '-': 1,
  '×': 2,
  '÷': 2,
  '%': 2,
};
